<a href="https://colab.research.google.com/github/danilopinho75/projetos-web-scraping/blob/main/web-scraping-e-sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercício

Faça a extração de alguma tabela da Wikipedia utilizando a biblioteca BeautifulSoup

##Setup

In [1]:
!pip install jupysql
!pip install beautifulsoup4

Requirement already satisfied: jupysql in /usr/local/lib/python3.10/dist-packages (0.10.12)
Requirement already satisfied: prettytable in /usr/local/lib/python3.10/dist-packages (from jupysql) (3.11.0)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.10/dist-packages (from jupysql) (2.0.32)
Requirement already satisfied: sqlparse in /usr/local/lib/python3.10/dist-packages (from jupysql) (0.5.1)
Requirement already satisfied: ipython-genutils>=0.1.0 in /usr/local/lib/python3.10/dist-packages (from jupysql) (0.2.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from jupysql) (3.1.4)
Requirement already satisfied: sqlglot>=11.3.7 in /usr/local/lib/python3.10/dist-packages (from jupysql) (20.11.0)
Requirement already satisfied: jupysql-plugin>=0.4.2 in /usr/local/lib/python3.10/dist-packages (from jupysql) (0.4.5)
Requirement already satisfied: ploomber-core>=0.2.7 in /usr/local/lib/python3.10/dist-packages (from jupysql) (0.2.25)
Requirement already satisfied: ploomber-extension in /usr/local/lib/python3.10/dist-packages (from jupysql) (0.1.1)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/dist-packages (from ploomber-core>=0.2.7->jupysql) (6.0.2)
Requirement already satisfied: posthog in /usr/local/lib/python3.10/dist-packages (from ploomber-core>=0.2.7->jupysql) (3.6.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->jupysql) (2.1.5)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prettytable->jupysql) (0.2.13)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy->jupysql) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy->jupysql) (3.0.3)
Requirement already satisfied: requests<3.0,>=2.7 in /usr/local/lib/python3.10/dist-packages (from posthog->ploomber-core>=0.2.7->jupysql) (2.32.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from posthog->ploomber-core>=0.2.7->jupysql) (1.16.0)
Requirement already satisfied: monotonic>=1.5 in /usr/local/lib/python3.10/dist-packages (from posthog->ploomber-core>=0.2.7->jupysql) (1.6)
Requirement already satisfied: backoff>=1.10.0 in /usr/local/lib/python3.10/dist-packages (from posthog->ploomber-core>=0.2.7->jupysql) (2.2.1)
Requirement already satisfied: python-dateutil>2.1 in /usr/local/lib/python3.10/dist-packages (from posthog->ploomber-core>=0.2.7->jupysql) (2.8.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0,>=2.7->posthog->ploomber-core>=0.2.7->jupysql) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0,>=2.7->posthog->ploomber-core>=0.2.7->jupysql) (3.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0,>=2.7->posthog->ploomber-core>=0.2.7->jupysql) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0,>=2.7->posthog->ploomber-core>=0.2.7->jupysql) (2024.8.30)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (4.12.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4) (2.6)

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import sqlite3

##Extração

In [3]:
#Fazer requisição GET e obter conteúdo HTML
url = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Paral%C3%ADmpicos_de_Ver%C3%A3o_de_2024"
response = requests.get(url)
html = response.content

#Criar objeto Beautiful Soup
soup = BeautifulSoup(html, "html.parser")

#Encontrar tabela desejada
table = soup.find_all("table", class_="wikitable")[0]

# Extrair os dados para uma lista
data = []
for row in table.find_all("tr"):
  cols = row.find_all("td")
  if cols:
    values = [col.text.strip() for col in cols]
    data.append(values)

In [4]:
data

[['1', 'CHN China', '94', '76', '50', '220', '1'],
 ['2', 'GBR Grã-Bretanha', '49', '44', '31', '124', '2'],
 ['3', 'USA Estados Unidos', '36', '42', '27', '105', '3'],
 ['4', 'NED Países Baixos', '27', '17', '12', '56', '9'],
 ['–', 'NPA Atletas Paralímpicos Neutros', '26', '22', '23', '71', '–'],
 ['5', 'BRA Brasil', '25', '26', '38', '89', '4'],
 ['6', 'ITA Itália', '24', '15', '32', '71', '7'],
 ['7', 'UKR Ucrânia', '22', '28', '32', '82', '5'],
 ['8', 'FRA França', '19', '28', '28', '75', '6'],
 ['9', 'AUS Austrália', '18', '17', '28', '63', '8'],
 ['10', 'JPN Japão', '14', '10', '17', '41', '11'],
 ['11', 'GER Alemanha', '10', '14', '25', '49', '10'],
 ['12', 'CAN Canadá', '10', '9', '10', '29', '15'],
 ['13', 'UZB Uzbequistão', '10', '9', '7', '26', '19'],
 ['14', 'IRI Irã', '8', '10', '7', '25', '20'],
 ['15', 'SUI Suíça', '8', '8', '5', '21', '22'],
 ['16', 'POL Polônia', '8', '6', '9', '23', '21'],
 ['17', 'ESP Espanha', '7', '11', '22', '40', '12'],
 ['18', 'IND Índia', '7', '9', '13', '29', '15'],
 ['19', 'COL Colômbia', '7', '7', '14', '28', '17'],
 ['20', 'BEL Bélgica', '7', '4', '3', '14', '26'],
 ['21', 'THA Tailândia', '6', '11', '13', '30', '13'],
 ['22', 'KOR Coreia do Sul', '6', '10', '14', '30', '13'],
 ['23', 'TUR Turquia', '6', '10', '12', '28', '17'],
 ['24', 'CUB Cuba', '6', '3', '1', '10', '33'],
 ['25', 'ALG Argélia', '6', '', '5', '11', '30'],
 ['26', 'HUN Hungria', '5', '6', '4', '15', '24'],
 ['27', 'TUN Tunísia', '5', '3', '3', '11', '30'],
 ['28', 'AZE Azerbaijão', '4', '2', '5', '11', '30'],
 ['29', 'ISR Israel', '4', '2', '4', '10', '33'],
 ['30', 'MEX México', '3', '6', '8', '17', '23'],
 ['31', 'MAR Marrocos', '3', '6', '6', '15', '24'],
 ['32', 'HKG Hong Kong', '3', '4', '1', '8', '39'],
 ['33', 'GRE Grécia', '3', '3', '7', '13', '28'],
 ['34', 'VEN Venezuela', '3', '2', '1', '6', '45'],
 ['35', 'SVK Eslováquia', '3', '2', '', '5', '50'],
 ['36', 'LAT Letônia', '3', '1', '', '4', '54'],
 ['37', 'ARG Argentina', '2', '3', '8', '13', '28'],
 ['38', 'DEN Dinamarca', '2', '3', '5', '10', '33'],
 ['39', 'KAZ Cazaquistão', '2', '3', '4', '9', '36'],
 ['40', 'NGR Nigéria', '2', '3', '2', '7', '41'],
 ['41', 'EGY Egito', '2', '2', '3', '7', '41'],
 ['42', 'MAS Malásia', '2', '2', '1', '5', '50'],
 ['43', 'POR Portugal', '2', '1', '4', '7', '41'],
 ['44', 'ETH Etiópia', '2', '1', '', '3', '60'],
 ['44', 'SIN Singapura', '2', '1', '', '3', '60'],
 ['46', 'RSA África do Sul', '2', '', '4', '6', '45'],
 ['47', 'ECU Equador', '2', '', '2', '4', '54'],
 ['48', 'JOR Jordânia', '2', '', '1', '3', '60'],
 ['40', 'CRC Costa Rica', '2', '', '', '2', '64'],
 ['50', 'INA Indonésia', '1', '8', '5', '14', '26'],
 ['51', 'GEO Geórgia', '1', '4', '4', '9', '36'],
 ['51', 'NZL Nova Zelândia', '1', '4', '4', '9', '36'],
 ['53', 'CZE Chéquia', '1', '4', '3', '8', '39'],
 ['54', 'NOR Noruega', '1', '3', '3', '7', '41'],
 ['55', 'IRL Irlanda', '1', '3', '2', '6', '45'],
 ['55', 'SRB Sérvia', '1', '3', '2', '6', '45'],
 ['57', 'MGL Mongólia', '1', '3', '', '4', '54'],
 ['58', 'IRQ Iraque', '1', '1', '3', '5', '50'],
 ['59', 'CRO Croácia', '1', '1', '2', '4', '54'],
 ['60', 'CHI Chile', '1', '', '4', '5', '50'],
 ['61', 'KUW Kuwait', '1', '', '1', '2', '64'],
 ['61', 'NAM Namíbia', '1', '', '1', '2', '64'],
 ['61', 'ROU Romênia', '1', '', '1', '2', '64'],
 ['61', 'SLO Eslovênia', '1', '', '1', '2', '64'],
 ['65', 'BUL Bulgária', '1', '', '', '1', '73'],
 ['65', 'KSA Arábia Saudita', '1', '', '', '1', '73'],
 ['65', 'PER Peru', '1', '', '', '1', '73'],
 ['68', 'TPE Taipé Chinês', '', '3', '2', '5', '50'],
 ['69', 'AUT Áustria', '', '3', '1', '4', '54'],
 ['70', 'BIH Bósnia e Herzegovina', '', '2', '', '2', '64'],
 ['71', 'FIN Finlândia', '', '1', '3', '4', '54'],
 ['72', 'SWE Suécia', '', '1', '2', '3', '60'],
 ['73', 'CYP Chipre', '', '1', '1', '2', '64'],
 ['73', 'MDA Moldávia', '', '1', '1', '2', '64'],
 ['75', 'KEN Quênia', '', '1', '', '1', '73'],
 ['75', 'SRI Sri Lanka', '', '1', '', '1', '73'],
 ['75', 'TTO Trinidad e Tobago', '', '1', '', '1', '73'],
 ['78', 'RPT Time Paralímpico de Refugiados', '', '', '2', '2', '64'],
 ['79', 'LTU Lituânia', '', '', '1', '1', '73'],
 ['79', 'LUX Luxemburgo', '', '', '1', '1', '73'],
 ['79', 'MNE Montenegro', '', '', '1', '1', '73'],
 ['79', 'MRI Maurício', '', '', '1', '1', '73'],
 ['79', 'NEP Nepal', '', '', '1', '1', '73'],
 ['79', 'PAK Paquistão', '', '', '1', '1', '73'],
 ['79', 'VIE Vietnã', '', '', '1', '1', '73']]

## Transformação

In [5]:
df = pd.DataFrame(data)

In [6]:
df

     0                                 1   2   3   4    5   6
0    1                         CHN China  94  76  50  220   1
1    2                  GBR Grã-Bretanha  49  44  31  124   2
2    3                USA Estados Unidos  36  42  27  105   3
3    4                 NED Países Baixos  27  17  12   56   9
4    –  NPA Atletas Paralímpicos Neutros  26  22  23   71   –
..  ..                               ...  ..  ..  ..  ...  ..
81  79                    MNE Montenegro           1    1  73
82  79                      MRI Maurício           1    1  73
83  79                         NEP Nepal           1    1  73
84  79                     PAK Paquistão           1    1  73
85  79                        VIE Vietnã           1    1  73

[86 rows x 7 columns]

In [7]:
df.columns = ["ordem", "pais", "medalha_de_ouro", "medalha_de_prata", "medalha_de_bronze", "total_de_medalhas", "ordem_por_total"]

In [8]:
df

,ordem,pais,medalha_de_ouro,medalha_de_prata,medalha_de_bronze,total_de_medalhas,ordem_por_total
0,1,CHN China,94,76,50,220,1
1,2,GBR Grã-Bretanha,49,44,31,124,2
2,3,USA Estados Unidos,36,42,27,105,3
3,4,NED Países Baixos,27,17,12,56,9
4,–,NPA Atletas Paralímpicos Neutros,26,22,23,71,–
...,...,...,...,...,...,...,...
81,79,MNE Montenegro,,,1,1,73
82,79,MRI Maurício,,,1,1,73
83,79,NEP Nepal,,,1,1,73
84,79,PAK Paquistão,,,1,1,73
85,79,VIE Vietnã,,,1,1,73

In [9]:
df.set_index("ordem", inplace=True)

In [10]:
df

,pais,medalha_de_ouro,medalha_de_prata,medalha_de_bronze,total_de_medalhas,ordem_por_total
ordem,,,,,,
1,CHN China,94,76,50,220,1
2,GBR Grã-Bretanha,49,44,31,124,2
3,USA Estados Unidos,36,42,27,105,3
4,NED Países Baixos,27,17,12,56,9
–,NPA Atletas Paralímpicos Neutros,26,22,23,71,–
...,...,...,...,...,...,...
79,MNE Montenegro,,,1,1,73
79,MRI Maurício,,,1,1,73
79,NEP Nepal,,,1,1,73
79,PAK Paquistão,,,1,1,73
79,VIE Vietnã,,,1,1,73

In [11]:
print(df.dtypes)

pais                 object
medalha_de_ouro      object
medalha_de_prata     object
medalha_de_bronze    object
total_de_medalhas    object
ordem_por_total      object
dtype: object

In [12]:
colunas_numericas = ['medalha_de_ouro', 'medalha_de_prata', 'medalha_de_bronze', 'total_de_medalhas', 'ordem_por_total']

# Converte as colunas numéricas e substitui valores inválidos por NaN
df[colunas_numericas] = df[colunas_numericas].apply(pd.to_numeric, errors='coerce')

# Preencher os NaN com zero
df[colunas_numericas] = df[colunas_numericas].fillna(0).astype(int)

In [13]:
print(df.dtypes)

pais                 object
medalha_de_ouro       int64
medalha_de_prata      int64
medalha_de_bronze     int64
total_de_medalhas     int64
ordem_por_total       int64
dtype: object

In [14]:
df

,pais,medalha_de_ouro,medalha_de_prata,medalha_de_bronze,total_de_medalhas,ordem_por_total
ordem,,,,,,
1,CHN China,94,76,50,220,1
2,GBR Grã-Bretanha,49,44,31,124,2
3,USA Estados Unidos,36,42,27,105,3
4,NED Países Baixos,27,17,12,56,9
–,NPA Atletas Paralímpicos Neutros,26,22,23,71,0
...,...,...,...,...,...,...
79,MNE Montenegro,0,0,1,1,73
79,MRI Maurício,0,0,1,1,73
79,NEP Nepal,0,0,1,1,73
79,PAK Paquistão,0,0,1,1,73
79,VIE Vietnã,0,0,1,1,73

## Carregamento

In [15]:
%load_ext sql

In [16]:
%%sql sqlite://

Connecting to 'sqlite://'

In [17]:
%sql --persist df

Running query in 'sqlite://'

Success! Persisted df to the database.

In [18]:
%%sql
SELECT * FROM df;

Running query in 'sqlite://'

+-------+----------------------------------+-----------------+------------------+-------------------+-------------------+-----------------+
| ordem |               pais               | medalha_de_ouro | medalha_de_prata | medalha_de_bronze | total_de_medalhas | ordem_por_total |
+-------+----------------------------------+-----------------+------------------+-------------------+-------------------+-----------------+
|   1   |            CHN China             |        94       |        76        |         50        |        220        |        1        |
|   2   |         GBR Grã-Bretanha         |        49       |        44        |         31        |        124        |        2        |
|   3   |        USA Estados Unidos        |        36       |        42        |         27        |        105        |        3        |
|   4   |        NED Países Baixos         |        27       |        17        |         12        |         56        |        9        |
|   –   | NPA Atletas Paralímpicos Neutros |        26       |        22        |         23        |         71        |        0        |
|   5   |            BRA Brasil            |        25       |        26        |         38        |         89        |        4        |
|   6   |            ITA Itália            |        24       |        15        |         32        |         71        |        7        |
|   7   |           UKR Ucrânia            |        22       |        28        |         32        |         82        |        5        |
|   8   |            FRA França            |        19       |        28        |         28        |         75        |        6        |
|   9   |          AUS Austrália           |        18       |        17        |         28        |         63        |        8        |
+-------+----------------------------------+-----------------+------------------+-------------------+-------------------+-----------------+
Truncated to displaylimit of 10.

## Consultas SQL

#### RANKING TOP 5 Países GERAL

In [34]:
%%sql

SELECT
  pais,
  total_de_medalhas,
  ordem_por_total
FROM df
WHERE ordem_por_total > 0
GROUP BY ordem_por_total
LIMIT 5

Running query in 'sqlite://'

+--------------------+-------------------+-----------------+
|        pais        | total_de_medalhas | ordem_por_total |
+--------------------+-------------------+-----------------+
|     CHN China      |        220        |        1        |
|  GBR Grã-Bretanha  |        124        |        2        |
| USA Estados Unidos |        105        |        3        |
|     BRA Brasil     |         89        |        4        |
|    UKR Ucrânia     |         82        |        5        |
+--------------------+-------------------+-----------------+

Fiz a consulta dos top 5 países que melhor rankearam na ordem total, ou seja, que mais possuíram medalhas.

#### Países com mais medalhas de ouro

In [35]:
%%sql
SELECT
  pais,
  medalha_de_ouro,
  ordem_por_total
FROM df
ORDER BY medalha_de_ouro DESC

Running query in 'sqlite://'

+----------------------------------+-----------------+-----------------+
|               pais               | medalha_de_ouro | ordem_por_total |
+----------------------------------+-----------------+-----------------+
|            CHN China             |        94       |        1        |
|         GBR Grã-Bretanha         |        49       |        2        |
|        USA Estados Unidos        |        36       |        3        |
|        NED Países Baixos         |        27       |        9        |
| NPA Atletas Paralímpicos Neutros |        26       |        0        |
|            BRA Brasil            |        25       |        4        |
|            ITA Itália            |        24       |        7        |
|           UKR Ucrânia            |        22       |        5        |
|            FRA França            |        19       |        6        |
|          AUS Austrália           |        18       |        8        |
+----------------------------------+-----------------+-----------------+
Truncated to displaylimit of 10.

Países baixos ficou em quarto de mais medalhas de ouro, mas não ficou entre os top 5 em quantidade de medalhas no geral

#### Percentual de medalhas